export default function Home({ data }) {
    const serverData = JSON.parse(data);

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to <a href="https://nextjs.org">Next.js! The time is {serverData.time}</a>
                </h1>
            </main>

            <footer className={styles.footer}>
                All right reserved.
            </footer>
        </div>
    );
}
